export type * from "./FirstParameter"
export type * from "./LastParameter"
export type * from "./NthParameter"
export type * from "./AnyFunction"
export type * from "./TailParameters"
export type * from "./InitParameters"
export type * from "./PickParameters"